services:
  mariadb:
    build:
      context: .
    stdin_open: true
    tty: true
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: CHANGEME
      MARIADB_DATABASE: mariadb
